### ISSUE TITLE
Design way to get back to clip view

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1020] opened 2016-03-06 05:42 UTC
When you close the zoomed clip there's no way to get back

**Comment by brampitoyo** [comment] 2016-03-06 20:47
Won’t the blue border around the highlighted area – which leads to the clip when clicked – solve this problem?

**Comment by ianb** [comment] 2016-03-06 21:18
I had forgotten about that part of the concept; but how would that work?  If the entire highlighted area is a click target, then you couldn't click on a link that was in that area – but being able to interact with the text of the clip seems like the most interesting part.  We could put a 🔍icon next to it?

**Comment by brampitoyo** [comment] 2016-03-06 22:27
Good point. If the entire area is clickable, then you won’t be able to select the text underneath.

I do like the 🔍 icon idea, and would like to propose two possible places to put it:

1. Middle of the clip 

<img width="195" alt="zoom-middle" src="https://cloud.githubusercontent.com/assets/51007/13557532/dfd13e7a-e456-11e5-9749-dc6e31637826.PNG">

The problem is, the icon obscures the content underneath that the user might like to highlight.

2. Top-right side of the clip.

<img width="197" alt="zoom-top-right" src="https://cloud.githubusercontent.com/assets/51007/13557535/fc15a8a0-e456-11e5-8520-abb7642dec5e.PNG">

The problem is, the metaphor is now confusing. You use the area to zoom into a clip, but then you can also close it?

So perhaps we want to change the metaphor into ‘zoom into clip’ and ‘zoom out of clip’. The close icon will have to be changed from an ‘x’ to a ‘zoom out’ icon.

Thoughts?

**Comment by fzzzy** [comment] 2016-03-10 14:51
I like the idea of using zoom in and zoom out buttons for this. I have implemented it, but I need some better icons.

**Closed** 2016-03-10 16:07 UTC
Labels: needs discussion
