### ISSUE TITLE
Move images out of main shot document

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#551] opened 2015-06-25 19:00 UTC
The main shot document is really large because of the images.  We should move them out.  That probably means a separate table.  We would figure out a way to rewrite the document to replace the big data URLs with normal URLs.  We'd have to figure out a way to garbage collect those images too, e.g., if a clip was deleted.

**Comment by fzzzy** [comment] 2015-07-08 15:08
Dupe of #554

**Closed by fzzzy** 2015-07-08 15:08 UTC
