### ISSUE TITLE
After making a selection, let me immediately re-select a different part of the page.

### ISSUE THREAD

**Issue by flukeout** [mozilla-services/pageshot#1635] opened 2016-09-29 19:44 UTC
Sometimes when I make a selection I'm not happy with, I'd like to re-select a different region of the page. Currently, clicking (or dragging) outside of the selected region clears the current selection.

I think a small improvement would be to do the following
* If I click outside of the selection, clear it
* If I click & drag outside of the selection, immediately start a new selection

**Comment by ianb** [comment] 2016-09-29 19:45
Agreed, duplicate of #1138

**Closed by ianb** 2016-09-29 19:45 UTC
