### ISSUE TITLE
Allow saving whole site as image

### ISSUE THREAD

**Issue by rugk** [mozilla-services/pageshot#1788] opened 2016-10-19 19:10 UTC
Similar to how the dev tools screen capture did it.

**Comment by ianb** [comment] 2016-10-19 19:11
Duplicate of #1613 – which is closed because it's implemented ;)  You should see the option in the next release, which is scheduled for early next week.

**Closed by ianb** 2016-10-19 19:11 UTC

**Comment by ianb** [comment] 2016-11-01 17:13
This feature was released in the [v1 release](https://discourse.mozilla-community.org/t/new-release-1-0-1-coming-this-week/11687/3) which went out on October 26th.
