### ISSUE TITLE
Unable to trigger error door hanger twice on same url

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1552] opened 2016-09-19 22:09 UTC
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18650503/46978c5a-7e7a-11e6-9622-2bc6e0ed2569.png)

### Actual results:

Error door hanger appears once, then never again (until/unless I refresh the page).

![pageshot-doorhanger](https://cloud.githubusercontent.com/assets/557895/18650492/310fc564-7e7a-11e6-95ff-807dd54513a6.gif)

### Expected results:

More errors. I was trying to take a screenshot for a previous bug, and finding that it's a one-and-done situation. I had to open a new tab to take the screenshot, or apparently I could have just refreshed the page.

Looking at the Browser Console, it looks like we may just have an edge case:

![browser_console_and_add-ons_manager_and_new_tab](https://cloud.githubusercontent.com/assets/557895/18650585/ad92d69e-7e7a-11e6-8feb-0e77c9cfc92c.png)
...
![jar_file____var_folders_qc_g_f0szh95k1fzph34rhmf5jw0000gp_t_edb68b47-432c-4592-b2f1-90ce443fb39d_extensions_jid1-neeaf3sahdkhpa_jetpack_xpi__lib_main_js_and_new_tab](https://cloud.githubusercontent.com/assets/557895/18650602/c7a79380-7e7a-11e6-9efc-bc04457b2158.png)

via [/addon/lib/main.js:225](https://github.com/mozilla-services/pageshot/blob/bb66ece08b1a773d9dbf18f16673e87ddac3656a/addon/lib/main.js#L225)

**Comment by ianb** [comment] 2016-09-19 22:12
Duplicate of #1377

**Closed by ianb** 2016-09-19 22:12 UTC
