### ISSUE TITLE
Escape should cancel selection

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#195] opened 2015-03-18 15:12 UTC
Right now we let you select forever – even if you are done with fiddling with the shot.

Maybe we also need some clear way to say "I'm done".  Not the same as deleting the shot, just done with the shot taking process.  Unfortunately when the panel closes it is very ambiguous *why* it closes, so it's hard to distinguish things like the panel hiding because of a click on the page vs a click on the PageShot button.

**Comment by brampitoyo** [comment] 2015-03-23 05:18
The “I’m done” functionality is really important because user should be able to get out of PageShot and restore normal page functionality: select/copy/paste text, drag image out to the desktop, etc.

However, by having “I’m done” on every selection, we prevent the user from being able to get a link in one click.

I want to give the user the ability to edit while preserving our core tenet of one-click-to-get-link.

To do this, every new selection is instantly confirmed. If user is unsatisfied by what was just selected, there’s an “Edit” button (alternatively, user can just delete and take another shot). To restore normal page functionality, user must exit this mode properly by clicking “I’m done” or “Cancel”.

#### New selection (when user clicks “+” to add a new selection, it’s considered new, too)

* PageShot is set on auto-detect. User clicks PageShot button. The doorhanger shows up, showing screenshot of auto-detected portion of the page, but *not* showing a lightbox on the page.

* PageShot is set on manual selection. User clicks PageShot button. The full-width crossbar appears and follows the mouse. On mouse drag, the crossbar changes into a lightbox. On mouse release, the lighbox disappear. Then the doorhanger shows up, showing screenshot of the selection portion of the page.

* Unsatisfied with the selection that we auto-detected or you have just made? The doorhanger has a button called “Edit”.

#### Edit selection

* Let’s say a user isn’t satisfied with the selection we automatically pick, or want to modify an area he manually selected the first time around. He clicks the “Edit” button on doorhanger. After clicking, the doorhanger disappears. A lightbox appears with two additional buttons alongside. “I’m done” saves the new selection. “Cancel” reverts the selection to the previously selected area.

* The user is free to fiddle infinitely, but cannot exit the mode or interact with the page normally until he clicks either “I’m done” or “Cancel”. After clicking, the lightbox disappear and the doorhanger appear again, showing screenshot of the selected portion of the page

 * Edit button is unavailable on full page shot. After all, full-page is supposed to take everything that’s visible on the screen. A full page shot can only be deleted or re-taken from scratch.

**Comment by ianb** [comment] 2015-03-23 15:29
> PageShot is set on auto-detect. User clicks PageShot button. The doorhanger shows up, showing screenshot of auto-detected portion of the page, but not showing a lightbox on the page.

I don't think the thumbnail of a selection is enough to understand exactly what was selected.  It's pretty small.  How about we show the lightbox as long as the panel is open (and the autoselection is applicable)?  In that case, if you click anywhere on the page the panel closes, and the lightbox goes away.  We could still allow resize (I think – timing could get tricky), but you couldn't create a brand-new selection like you can now.

**Comment by brampitoyo** [comment] 2015-03-24 06:25
I like your idea a lot. Let’s do it.

Right now, we have this conflict between:

* Wanting to show a lightbox. It will help user visually connect a selected area and its thumbnail on the doorhanger.
* Wanting each selection to be editable. Deleting a selection in order to retake it is baffling. Why not have an edit mode?
* Wanting the full functionality of the page to be available quickly. Otherwise, user is stuck in lightbox mode or edit mode forever and can’t do normal page operation.

[This video](http://f.cl.ly/items/3k1q471K3x1j0f323W0y/pageshot-auto-detect-behaviour.mov) goes into the behaviour in detail.

#### Briefly

* Clicking the PageShot button while *Auto-detect* is set to default will open the doorhanger and display the lightbox. Let’s call this *lightbox mode*.
* To dismiss lightbox mode:
  * Click the PageShot button again
  * Click anywhere outside of the doorhanger (as long as it’s not within the selection box)
  * Hit *escape* key
* To enter edit mode:
  * While lightbox mode is active and the doorhanger is open, hover mouse close to the selection box
  * Imagine the selection box as having a 20x20 pixels border around it. Whenever the mouse is hovered over the box or its surrounding border, the box shows resize handles on its eight corners
  * When user click anywhere inside this area (or click-and-drag on the handle), the doorhanger is closed *but* the lightbox stays present. This is the *edit mode*.
  * On edit mode, the lightbox is persistent until dismissed, either with *cancel/escape* or *done/enter*
  * After dismissed, the resize handles around the box disappear *but* the lightbox still remains. The doorhanger panel reappears, showing the latest thumbnails.

##### Keyboard shortcuts

* *Escape* will cancel edit mode and close doorhanger
  * Canceling edit mode will bring up the doorhanger again with the lightbox highlighted
  * Closing doorhanger will dismiss the lightbox
  * So to go from edit back to vanilla page, user can simply hit the *escape* key twice
* *Return/enter* will confirm edit mode (the equivalent of clicking the *Done* button)

**Comment by ianb** [comment] 2015-05-06 15:35
Besides bugs, I think the behavior for closing or hiding the shot is now good.

**Comment by fzzzy** [comment] 2016-03-14 21:24
I guess I'll make a new issue instead of reopening this one

**Closed by fzzzy** 2016-03-14 21:24 UTC
