### ISSUE TITLE
GA track user activity

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#634] opened 2015-07-30 00:52 UTC
We can [track user activity](https://pageshot.dev.mozaws.net/jdrzw0yo/developers.google.com), for example navigating clips

**Comment by fzzzy** [comment] 2015-09-29 15:52
Change existing ga calls for install and install-banner; category should be install for both; actions should be homepage and banner.

Let's see if we can change the urls that get passed to google to have XXX over the id or to leave the url out entirely, for privacy reasons.

**Comment by fzzzy** [comment] 2015-09-30 15:35
dupe of #762

**Closed by fzzzy** 2015-09-30 15:35 UTC
